all: refs refs_test nativeLazyStreams streamstrees music

refs: refs.ml
	ocamlbuild refs.byte

refs_test: refs_test.ml
	ocamlbuild refs_test.byte

nativeLazyStreams: nativeLazyStreams.ml
	ocamlbuild nativeLazyStreams.byte

streamstrees: streamstrees.ml
	ocamlbuild streamstrees.byte

music: music.ml
	ocamlbuild music.byte


